package models

var EVENT_TYPE_VMS_SERVER_UPDATE = 2001
var EVENT_TYPE_VMS_SERVER_UPDATE_TYPE = "VMS-SERVER-UPDATE"

var EVENT_TYPE_HR_SERVER_UPDATE = 2005
var EVENT_TYPE_HR_SERVER_UPDATE_TYPE = "HR-SERVER-UPDATE"

var EVENT_TYPE_RFID_SERVER_UPDATE = 2006
var EVENT_TYPE_RFID_SERVER_UPDATE_TYPE = "RFID-SERVER-UPDATE"

var EVENT_TYPE_KIOSK_LOCATION_CREATE = 2002
var EVENT_TYPE_KIOSK_LOCATION_CREATE_TYPE = "KIOSK-LOCATION-CREATE"

var EVENT_TYPE_KIOSK_LOCATION_UPDATE = 2003
var EVENT_TYPE_KIOSK_LOCATION_UPDATE_TYPE = "KIOSK-LOCATION-UPDATE"

var EVENT_TYPE_KIOSK_LOCATION_DELETE = 2004
var EVENT_TYPE_KIOSK_LOCATION_DELETE_TYPE = "KIOSK-LOCATION-DELETE"

var EVENT_TYPE_BRIDGE_LOG_RETENTION_CHECK = 2007
var EVENT_TYPE_BRIDGE_LOG_RETENTION_CHECK_TYPE = "BRIDGE_LOG-CHECK"

var EVENT_TYPE_HR_RECORDS_RETENTION_CHECK = 20071
var EVENT_TYPE_HR_RECORDS_RETENTION_CHECK_TYPE = "HR-RECORDS-CHECK"

var EVENT_TYPE_VMS_RECORDS_RETENTION_CHECK = 20072
var EVENT_TYPE_VMS_RECORDS_RETENTION_CHECK_TYPE = "VMS-RECORDS-CHECK"

var EVENT_TYPE_RFID_SERVER_CONNECT_SUCCESS = 2008
var EVENT_TYPE_RFID_SERVER_CONNECT_SUCCESS_TYPE = "RFID-CONNECT-SUCCESS"

var EVENT_TYPE_VMS_SERVER_CONNECT_SUCCESS = 20081
var EVENT_TYPE_VMS_SERVER_CONNECT_SUCCESS_TYPE = "VMS-CONNECT-SUCCESS"

var EVENT_TYPE_HR_SERVER_CONNECT_SUCCESS = 20082
var EVENT_TYPE_HR_SERVER_CONNECT_SUCCESS_TYPE = "HR-CONNECT-SUCCESS"

var EVENT_TYPE_RFID_SERVER_CONNECT_FAIL = 2009
var EVENT_TYPE_RFID_SERVER_CONNECT_FAIL_TYPE = "RFID-CONNECT-FAIL"

var EVENT_TYPE_VMS_SERVER_CONNECT_FAIL = 20091
var EVENT_TYPE_VMS_SERVER_CONNECT_FAIL_TYPE = "VMS-CONNECT-FAIL"

var EVENT_TYPE_HR_SERVER_CONNECT_FAIL = 20092
var EVENT_TYPE_HR_SERVER_CONNECT_FAIL_TYPE = "HR-CONNECT-FAIL"

var EVENT_TYPE_VMS_KIOSK_REPORTS_SYNC_START = 2010
var EVENT_TYPE_VMS_KIOSK_REPORTS_SYNC_START_TYPE = "VMS-KIOSK-REPORTS-SYNC-START"

var EVENT_TYPE_VMS_KIOSK_REPORTS_SYNC_DONE = 2011
var EVENT_TYPE_VMS_KIOSK_REPORTS_SYNC_DONE_TYPE = "VMS-KIOSK-REPORTS-SYNC-DONE"

var EVENT_TYPE_VMS_KIOSK_REPORTS_SYNC_FAIL = 2012
var EVENT_TYPE_VMS_KIOSK_REPORTS_SYNC_FAIL_TYPE = "VMS-KIOSK-REPORTS-SYNC-FAIL"

var EVENT_TYPE_VMS_KIOSK_DEVICE_SYNC_SUCCESS = 2013
var EVENT_TYPE_VMS_KIOSK_DEVICE_SYNC_SUCCESS_TYPE = "VMS-KIOSK-DEVICE-SYNC-SUCCESS"

var EVENT_TYPE_VMS_KIOSK_DEVICE_SYNC_FAIL = 2014
var EVENT_TYPE_VMS_KIOSK_DEVICE_SYNC_FAIL_TYPE = "VMS-KIOSK-DEVICE-SYNC-FAIL"

var EVENT_TYPE_HR_SERVER_SYNC_FAIL = 2015
var EVENT_TYPE_HR_SERVER_SYNC_FAIL_TYPE = "HR-SERVER-SYNC-FAIL"

var EVENT_TYPE_HR_SERVER_SYNC_SUCCESS = 2016
var EVENT_TYPE_HR_SERVER_SYNC_SUCCESS_TYPE = "HR-SERVER-SYNC-SUCCESS"

var EVENT_TYPE_VMS_SERVER_SYNC_SUCCESS = 2017
var EVENT_TYPE_VMS_SERVER_SYNC_SUCCESS_TYPE = "VMS-SERVER-SYNC-SUCCESS"

var EVENT_TYPE_VMS_SERVER_SYNC_FAIL = 2018
var EVENT_TYPE_VMS_SERVER_SYNC_FAIL_TYPE = "VNS-SERVER-SYNC-FAIL"





