package models


var EVENT_TYPE_USER_LOGIN = 10001
var EVENT_TYPE_USER_LOGIN_TYPE = "LOGIN"
var EVENT_TYPE_USER_LOGIN_FAIL = 100014
var EVENT_TYPE_USER_LOGIN_FAIL_TYPE = "LOGIN-FAIL"

var EVENT_TYPE_USER_LOGOUT = 10002
var EVENT_TYPE_USER_LOGOUT_TYPE = "LOGOUT"
var EVENT_TYPE_USER_LOGOUT_FAIL = 100024
var EVENT_TYPE_USER_LOGOUT_FAIL_TYPE = "LOGOUT-FAIL"

var EVENT_TYPE_COMPANY_EDIT = 10003
var EVENT_TYPE_COMPANY_EDIT_TYPE = "COMPANY-EDIT"

var EVENT_TYPE_TEMPLATE_CREATE = 10004
var EVENT_TYPE_TEMPLATE_CREATE_TYPE = "TEMPLATE-CREATE"

var EVENT_TYPE_TEMPLATE_EDIT = 10005
var EVENT_TYPE_TEMPLATE_EDIT_TYPE = "TEMPLATE-EDIT"

var EVENT_TYPE_TEMPLATE_DELETE = 10006
var EVENT_TYPE_TEMPLATE_DELETE_TYPE = "TEMPLATE-DELETE"

var EVENT_TYPE_KIOSK_DEVICE_CONNECT = 10007
var EVENT_TYPE_KIOSK_DEVICE_CONNECT_TYPE = "KIOSK-DEVICE-ADD"

var EVENT_TYPE_KIOSK_DEVICE_EDIT = 10008
var EVENT_TYPE_KIOSK_DEVICE_EDIT_TYPE = "KIOSK-DEVICE-EDIT"

var EVENT_TYPE_KIOSK_DEVICE_REMOVE = 10009
var EVENT_TYPE_KIOSK_DEVICE_REMOVE_TYPE = "KIOSK-DEVICE-REMOVE"

var EVENT_TYPE_PERSON_CREATE = 10010
var EVENT_TYPE_PERSON_CREATE_TYPE = "PERSON-CREATE"

var EVENT_TYPE_PERSON_EDIT = 10011
var EVENT_TYPE_PERSON_EDIT_TYPE = "PERSON-EDIT"

var EVENT_TYPE_PERSON_DELETE = 10012
var EVENT_TYPE_PERSON_DELETE_TYPE = "PERSON-DELETE"

var EVENT_TYPE_CHECK_IN_REPORTS_READ = 10013
var EVENT_TYPE_CHECK_IN_REPORTS_READ_TYPE = "CHECKIN-REPORTS-READ"

var EVENT_TYPE_ATTENDANCE_READ = 10014
var EVENT_TYPE_ATTENDANCE_READ_TYPE = "ATTENDANCE-READ"

var EVENT_TYPE_PERSON_IMPORT_BATCH = 10015
var EVENT_TYPE_PERSON_IMPORT_BATCH_TYPE = "PERSON-IMPORT"

var EVENT_TYPE_USER_CREATE = 10016
var EVENT_TYPE_USER_CREATE_TYPE = "USER-CREATE"

var EVENT_TYPE_USER_EDIT = 10017
var EVENT_TYPE_USER_EDIT_TYPE = "USER-EDIT"

var EVENT_TYPE_USER_DELETE = 10018
var EVENT_TYPE_USER_DELETE_TYPE = "USER-DELETE"

var EVENT_TYPE_SMTP_TEST = 10019
var EVENT_TYPE_SMTP_TEST_TYPE = "SMTP-TEST"

var EVENT_TYPE_RETENTION_UPDATE = 10020
var EVENT_TYPE_RETENTION_UPDATE_TYPE = "RETENTION-UPDATE"

var EVENT_TYPE_SMTP_UPDATE = 10021
var EVENT_TYPE_SMTP_UPDATE_TYPE = "SMTP-UPDATE"

var EVENT_TYPE_LICENSE_REGISTER = 10022
var EVENT_TYPE_LICENSE_REGISTER_TYPE = "LICENSE-REGISTER"

var EVENT_TYPE_LOG_EXPORT = 10023
var EVENT_TYPE_LOG_EXPORT_TYPE = "LOG-EXPORT"
